// <auto-generated />
using System;
using GroundManagmentSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroundManagmentSystem.Migrations
{
    [DbContext(typeof(Ground_Managment_System_Db_context))]
    [Migration("20220226144537_new")]
    partial class @new
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GroundManagmentSystem.Models.ISA_Model", b =>
                {
                    b.Property<int>("ISA_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ISA_id"), 1L, 1);

                    b.Property<int>("ISA_ac")
                        .HasColumnType("int");

                    b.Property<int>("ISA_ac_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_bc")
                        .HasColumnType("int");

                    b.Property<int>("ISA_bc_value")
                        .HasColumnType("int");

                    b.Property<string>("ISA_comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISA_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ISA_date_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("ISA_fba")
                        .HasColumnType("int");

                    b.Property<int>("ISA_fba_palets_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_fba_sea_container")
                        .HasColumnType("int");

                    b.Property<int>("ISA_fba_standard")
                        .HasColumnType("int");

                    b.Property<int>("ISA_hc")
                        .HasColumnType("int");

                    b.Property<int>("ISA_hc_value")
                        .HasColumnType("int");

                    b.Property<string>("ISA_hour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ISA_lp")
                        .HasColumnType("int");

                    b.Property<int>("ISA_lp_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_mono")
                        .HasColumnType("int");

                    b.Property<int>("ISA_mono_value")
                        .HasColumnType("int");

                    b.Property<long>("ISA_number")
                        .HasColumnType("bigint");

                    b.Property<int>("ISA_parcel")
                        .HasColumnType("int");

                    b.Property<int>("ISA_parcel_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_pax")
                        .HasColumnType("int");

                    b.Property<int>("ISA_pax_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_ra")
                        .HasColumnType("int");

                    b.Property<int>("ISA_ra_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_rap")
                        .HasColumnType("int");

                    b.Property<int>("ISA_rap_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_rb")
                        .HasColumnType("int");

                    b.Property<int>("ISA_rb_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_rbp")
                        .HasColumnType("int");

                    b.Property<int>("ISA_rbp_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_rh")
                        .HasColumnType("int");

                    b.Property<int>("ISA_rh_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_rhp")
                        .HasColumnType("int");

                    b.Property<int>("ISA_rhp_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_semitrailer")
                        .HasColumnType("int");

                    b.Property<string>("ISA_to_chceck")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ISA_units")
                        .HasColumnType("int");

                    b.HasKey("ISA_id");

                    b.ToTable("ISA_Models");
                });

            modelBuilder.Entity("GroundManagmentSystem.Models.Line_Model", b =>
                {
                    b.Property<int>("LINE_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LINE_id"), 1L, 1);

                    b.Property<short>("LINE_ac")
                        .HasColumnType("smallint");

                    b.Property<int>("LINE_asign_isa")
                        .HasColumnType("int");

                    b.Property<short>("LINE_bc")
                        .HasColumnType("smallint");

                    b.Property<string>("LINE_comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("LINE_fba")
                        .HasColumnType("smallint");

                    b.Property<short>("LINE_hc")
                        .HasColumnType("smallint");

                    b.Property<short>("LINE_lp")
                        .HasColumnType("smallint");

                    b.Property<short>("LINE_mono")
                        .HasColumnType("smallint");

                    b.Property<int>("LINE_number")
                        .HasColumnType("int");

                    b.Property<short>("LINE_parcel")
                        .HasColumnType("smallint");

                    b.Property<short>("LINE_pax")
                        .HasColumnType("smallint");

                    b.Property<short>("LINE_ra")
                        .HasColumnType("smallint");

                    b.Property<short>("LINE_rap")
                        .HasColumnType("smallint");

                    b.Property<short>("LINE_rb")
                        .HasColumnType("smallint");

                    b.Property<short>("LINE_rbp")
                        .HasColumnType("smallint");

                    b.Property<short>("LINE_rh")
                        .HasColumnType("smallint");

                    b.Property<short>("LINE_rhp")
                        .HasColumnType("smallint");

                    b.Property<short>("LINE_sea_container")
                        .HasColumnType("smallint");

                    b.Property<short>("LINE_semitrailer")
                        .HasColumnType("smallint");

                    b.Property<short>("LINE_standard")
                        .HasColumnType("smallint");

                    b.Property<short>("LINE_to_check")
                        .HasColumnType("smallint");

                    b.Property<int>("LINE_units")
                        .HasColumnType("int");

                    b.HasKey("LINE_id");

                    b.ToTable("Line_Models");
                });
#pragma warning restore 612, 618
        }
    }
}
