// <auto-generated />
using System;
using GroundManagmentSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroundManagmentSystem.Migrations
{
    [DbContext(typeof(Ground_Managment_System_Db_context))]
    [Migration("20220527035216_MySql")]
    partial class MySql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GroundManagmentSystem.Models.ISA_Model", b =>
                {
                    b.Property<int>("ISA_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ISA_ac")
                        .HasColumnType("int");

                    b.Property<int>("ISA_ac_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_bc")
                        .HasColumnType("int");

                    b.Property<int>("ISA_bc_value")
                        .HasColumnType("int");

                    b.Property<string>("ISA_comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ISA_date_time")
                        .HasColumnType("datetime");

                    b.Property<int>("ISA_fba")
                        .HasColumnType("int");

                    b.Property<int>("ISA_fba_sea_container")
                        .HasColumnType("int");

                    b.Property<int>("ISA_fba_standard")
                        .HasColumnType("int");

                    b.Property<int>("ISA_hc")
                        .HasColumnType("int");

                    b.Property<int>("ISA_hc_value")
                        .HasColumnType("int");

                    b.Property<DateTime>("ISA_last_update")
                        .HasColumnType("datetime");

                    b.Property<string>("ISA_line")
                        .HasColumnType("longtext");

                    b.Property<int>("ISA_lp")
                        .HasColumnType("int");

                    b.Property<int>("ISA_lp_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_mono")
                        .HasColumnType("int");

                    b.Property<int>("ISA_mono_value")
                        .HasColumnType("int");

                    b.Property<long>("ISA_number")
                        .HasColumnType("bigint");

                    b.Property<int>("ISA_parcel")
                        .HasColumnType("int");

                    b.Property<int>("ISA_parcel_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_pax")
                        .HasColumnType("int");

                    b.Property<int>("ISA_pax_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_ra")
                        .HasColumnType("int");

                    b.Property<int>("ISA_ra_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_rap")
                        .HasColumnType("int");

                    b.Property<int>("ISA_rap_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_rb")
                        .HasColumnType("int");

                    b.Property<int>("ISA_rb_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_rbp")
                        .HasColumnType("int");

                    b.Property<int>("ISA_rbp_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_rh")
                        .HasColumnType("int");

                    b.Property<int>("ISA_rh_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_rhp")
                        .HasColumnType("int");

                    b.Property<int>("ISA_rhp_value")
                        .HasColumnType("int");

                    b.Property<int>("ISA_semitrailer")
                        .HasColumnType("int");

                    b.Property<bool>("ISA_to_chceck")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ISA_units")
                        .HasColumnType("int");

                    b.HasKey("ISA_id");

                    b.ToTable("ISA_Models");
                });
#pragma warning restore 612, 618
        }
    }
}
